mixed-port: 7890
ipv6: true
allow-lan: true
mode: rule
log-level: info
unified-delay: false
geo-auto-update: true
geo-update-interval: 168
external-controller: 127.0.0.1:9090
secret: Hpp@19921992
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  respect-rules: true
  use-hosts: true
  nameserver:
  - https://1.1.1.1/dns-query
  - https://8.8.8.8/dns-query
  proxy-server-nameserver:
  - 178.22.122.100
  - 185.51.200.2
  nameserver-policy:
    domain:+.ir:
    - proxy-server-nameserver
    all:
    - nameserver
tun:
  enable: true
  stack: gvisor
  auto-route: true
  strict-route: true
  auto-detect-interface: true
  dns-hijack:
  - tcp://any:53
  - udp://any:53
  mtu: 1330
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  sniff:
    HTTP:
      ports:
      - 80
      - 8080
      - 8880
      - 2052
      - 2082
      - 2086
      - 2095
    TLS:
      ports:
      - 443
      - 8443
      - 2053
      - 2083
      - 2087
      - 2096
    QUIC:
      ports:
      - 443
      - 8443
proxies:
- name: Auto-1
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Auto-2
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Auto-3
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Auto-4
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Auto-5
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Auto-6
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Auto-7
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Auto-8
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Auto-9
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Auto-10
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Auto-11
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Auto-12
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Auto-13
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Auto-14
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Auto-15
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Auto-16
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Auto-17
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Auto-18
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Auto-19
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Auto-20
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Auto-21
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Auto-22
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Auto-23
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Auto-24
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Auto-25
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Auto-26
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Auto-27
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Auto-28
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Auto-29
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Auto-30
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Auto-31
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Auto-32
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Auto-33
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Auto-34
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Auto-35
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Auto-36
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Auto-37
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Auto-38
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Auto-39
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Auto-40
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Auto-41
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Auto-42
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Auto-43
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Auto-44
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Auto-45
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Auto-46
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Auto-47
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Auto-48
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Auto-49
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Auto-50
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Proxy-51
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Proxy-52
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Proxy-53
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Proxy-54
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Proxy-55
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Proxy-56
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Proxy-57
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Proxy-58
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Proxy-59
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Proxy-60
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Proxy-61
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Proxy-62
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Proxy-63
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Proxy-64
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Proxy-65
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Proxy-66
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Proxy-67
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Proxy-68
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Proxy-69
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Proxy-70
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Proxy-71
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Proxy-72
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Proxy-73
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Proxy-74
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Proxy-75
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Proxy-76
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Proxy-77
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Proxy-78
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Proxy-79
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
- name: Proxy-80
  type: ss
  server: 127.0.0.1
  port: 443
  cipher: chacha20-ietf-poly1305
  password: dummy
  udp: true
proxy-groups:
- name: 💚خانه
  type: select
  proxies:
  - اتصال❤️خودکار
- name: اتصال❤️خودکار
  type: url-test
  url: http://www.google.com/generate_204
  interval: 180
  tolerance: 100
  proxies:
  - Proxy-1
  - Proxy-2
  - Proxy-3
  - Proxy-4
  - Proxy-5
  - Proxy-6
  - Proxy-7
  - Proxy-8
  - Proxy-9
  - Proxy-10
  - Proxy-11
  - Proxy-12
  - Proxy-13
  - Proxy-14
  - Proxy-15
  - Proxy-16
  - Proxy-17
  - Proxy-18
  - Proxy-19
  - Proxy-20
  - Proxy-21
  - Proxy-22
  - Proxy-23
  - Proxy-24
  - Proxy-25
  - Proxy-26
  - Proxy-27
  - Proxy-28
  - Proxy-29
  - Proxy-30
  - Proxy-31
  - Proxy-32
  - Proxy-33
  - Proxy-34
  - Proxy-35
  - Proxy-36
  - Proxy-37
  - Proxy-38
  - Proxy-39
  - Proxy-40
  - Proxy-41
  - Proxy-42
  - Proxy-43
  - Proxy-44
  - Proxy-45
  - Proxy-46
  - Proxy-47
  - Proxy-48
  - Proxy-49
  - Proxy-50
  - Proxy-51
  - Proxy-52
  - Proxy-53
  - Proxy-54
  - Proxy-55
  - Proxy-56
  - Proxy-57
  - Proxy-58
  - Proxy-59
  - Proxy-60
  - Proxy-61
  - Proxy-62
  - Proxy-63
  - Proxy-64
  - Proxy-65
  - Proxy-66
  - Proxy-67
  - Proxy-68
  - Proxy-69
  - Proxy-70
  - Proxy-71
  - Proxy-72
  - Proxy-73
  - Proxy-74
  - Proxy-75
  - Proxy-76
  - Proxy-77
  - Proxy-78
  - Proxy-79
  - Proxy-80
rules:
- MATCH,💚خانه
