mixed-port: 7890
ipv6: true
allow-lan: true
mode: rule
log-level: info
keepalive: 25
keep-alive-idle: 10
keep-alive-interval: 15
unified-delay: false
geo-auto-update: true
geo-update-interval: 168
external-controller: 127.0.0.1:9090
secret: Hpp@19921992
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
external-controller-cors:
  allow-origins:
  - '*'
  allow-private-network: true
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  respect-rules: true
  use-hosts: true
  use-system-hosts: false
  nameserver:
  - https://1.1.1.1/dns-query
  - https://8.8.8.8/dns-query
  - https://dns.quad9.net/dns-query
  proxy-server-nameserver:
  - 178.22.122.100
  - 185.51.200.2
  - 10.202.10.10
  - 10.202.10.11
  nameserver-policy:
    domain:+.ir:
    - proxy-server-nameserver
    all:
    - nameserver
  fallback-filter:
    geoip: true
    geoip-code: IR
    ipcidr:
    - 240.0.0.0/4
    geosite:
    - cn
    domain:
    - +.ir
tun:
  enable: true
  stack: gvisor
  auto-route: true
  strict-route: true
  auto-detect-interface: true
  dns-hijack:
  - tcp://any:53
  - udp://any:53
  mtu: 1330
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: false
  sniff:
    HTTP:
      ports:
      - 80
      - 8080
      - 8880
      - 2052
      - 2082
      - 2086
      - 2095
    TLS:
      ports:
      - 443
      - 8443
      - 2053
      - 2083
      - 2087
      - 2096
    QUIC:
      ports:
      - 443
      - 8443
proxies: []
proxy-groups:
- name: 💚خانه
  type: select
  proxies:
  - اتصال❤️خودکار
- name: اتصال❤️خودکار
  type: url-test
  url: http://www.google.com/generate_204
  interval: 120
  tolerance: 100
  proxies: []
rule-providers: {}
rules:
- MATCH,💚خانه
